### ISSUE TITLE
Duplicate field name: no error raised

### ISSUE THREAD

**Issue by MarcoAlbaETT** [Swiss-Polar-Institute/frictionless-data-packages#4]
If tableschema contains the same field name more than once, the data are valid and no error is raised when reading the data.
I get an error when I try to create a NetCDF file from the schema (duplicate variables name not allowed)
See 10.5281_zenodo.3634411; the field "Ni_flags" is defined twice in tableschema and also in the original csv file.

**Comment by cpina** [comment]
As a curiosity: the package "goodtables" raises an error in this case (unless `goodtables --skip-checks check_name_i_cant_remember`). When I implemented the validator I didn't know that goodtables could be used to validate full data packages but I plan to add extra validations using goodtables as well.

The frictionless data specification allow to have duplicated column names (I guess that it's good to be able to describe not optimal tabular data!). We can discuss what to do in this package tomorrow (@jen-thomas might have some ideas :-) )

**Comment by cpina** [comment]
Related to this: https://github.com/Swiss-Polar-Institute/frictionless-data-packages/issues/3

**Comment by jen-thomas** [comment]
For this particular dataset I've notified the scientist so they can correct the dataset in Zenodo. 

Related to this: we should perhaps discuss how to deal with changes / updates to datasets.
eg. correction -> new version -> new DOI

**Comment by cpina** [comment]
I've moved this dataset to the branch `pending_changes`.

We are now using `goodtables` to detect this earlier.

With the `x_spi_netcdf_name` we could technically avoid this issue but we can discuss this later (if the CSV can be fixed or we have another temporary fix).
